# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 633a489ccd4e86b460d225a42deb4ac8de823e021cf7ce3e376be835ff5a9453f8b95eae2c2c69b83f39a03444591f0cd915d789a5ba2c08e4f329b382eeb631

test:
  secret_key_base: 1f15432488d5c92539ebd15f8d601a9621f5e4839c4fe9d250783cc699ce6e260ce60431770318c0a39f1e6f016eed8a13173f42c93a20dbe427de3e39bff51b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
